live_config_reload = true

# From iTerm2 Pastel Dark theme
# Default colors
[colors.primary]
background = '#000000'
foreground = '#C7C7C7'

# Cursor colors
[colors.cursor]
text    = '#FFFEFF'
cursor  = '#FFB472'

# Normal colors
[colors.normal]
black    = '#616161'
red      = '#FF8272'
green    = '#B4FA72'
yellow   = '#FEFDC2'
blue     = '#A5D5FE'
magenta  = '#FF8FFD'
cyan     = '#D0D1FE'
white    = '#F1F1F1'

# Bright colors
[colors.bright]
black    = '#8E8E8E'
red      = '#FFC4BD'
green    = '#D6FCB9'
yellow   = '#FEFDD5'
blue     = '#C1E3FE'
magenta  = '#FFB1FE'
cyan     = '#E5E6FE'
white    = '#FFFEFF'

[cursor]
style = { shape = "Block", blinking = "On" }

[env]
# This isn't working for now. Not sure what the problem is or if it matters
#TERM = "alacritty"

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[scrolling]
history = 100000

[window]
dynamic_title = true
title = "Alacritty Terminal"
startup_mode = "Maximized"
